# SPDX-FileCopyrightText: 2021 Gabriel J. Schwarzkopf <sispo-devs@outlook.com>
#
# SPDX-License-Identifier: CC0-1.0
# SPDX-License-Identifier: GPL-3.0-or-later

name: sispo
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy=4.2.1
  - astroquery=0.4.1
  - python=3.9
  - pip
  - setuptools
  - numpy=1.19.2
  - numpy-base=1.19.2
  - orekit=10.3
  - opencv=4.5.0
  - pip:
    - OpenEXR==1.3.2
